### ISSUE TITLE
Mobile support via USB / WiFi

### ISSUE THREAD

**Issue by socketing** [baku89/tethr#1]
I'd like to know if your open source supports Android. I really want to use WiFi or USB to control the camera on Android system.

**Comment by baku89** [comment]
Thank you for the suggestion;) I'm now writing a fallback logic to webcam MediaStream so it surely will support Android and other smartphones.

**Comment by baku89** [comment]
Hey, I just finished writing webcam fallback which also works on Android.

The known issue so far is that the `facingMode` config which specifies rear/front cameras somehow seems to have duplicated options in some models. (On Pixel 3, a front camera is listed as three separated options `camera 2 1, facing front`, `camera 2 2, facing front`, `camera 2 3, facing front`.)
